## infra node'lar için vlan örneği

apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan150-infra-1
spec:
  nodeSelector:
    kubernetes.io/hostname: infra-1-fqdn
  maxUnavailable: 1
  desiredState:
    interfaces:
      - name: ens35
        description: "VLAN150 secondary IP"
        type: ethernet
        state: up
        ipv4:
          dhcp: false
          enabled: true
          address:
            - ip: 10.150.0.11
              prefix-length: 24
              
    # Routing Kuralları (PBR)
    route-rules:
      config:
      - priority: 100
        route-table: 150  #tablo id
        from: 10.0.150.10/32  #node ip, bare metal worker'de egress kullanılacaksa burada /24 ile tüm network olmalı.
    
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 10.0.150.1  #gateway
        next-hop-interface: ens35  #interface
        table-id: 150  #yukarıdaki tablo id
